---
- name: running command to see the display_name
  command: xe vm-list name-label="{{ xen_display_name }}"
  register: power_state

- name: failed
  fail:
    mesg: "test"
  when: power_state.stdout.find('running') != -1

- name: copy vm creation script
  template: src=create.sh.j2 dest=/root/create.sh mode=0755

- name: running script
  command: /root/create.sh

- name: upload create template script
  template: src=template.sh.j2 dest=/root/template.sh mode=0755
